---
language: python

python:
  - 2.7

services:
  - docker

script:
  # Build Docker Container
  - docker build -t todoist-python .

  # Test importing todoist module  
  - docker run -it --rm --name python-test todoist-python python -c "import todoist"

  # Test that I can init Todoist Library with an api key
  - |
    docker run -it --rm --name python-test todoist-python python -c "import todoist
    api = todoist.TodoistAPI()
    if type(api) != todoist.api.TodoistAPI:
      raise Exception('API was %s but todoist.api.TodoistAPI was expected' % type(api))"
...
